version: '3.8'

services:
  client:
    build:
      context: ./client
      target: production_stage
    volumes:
      - ./client:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development